# Generated by Django 4.2.16 on 2024-11-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_review',
        ),
    ]
