# Generated by Django 4.2.16 on 2024-11-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comment_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
